<?php
/*
 * Created on May 25, 2009
 */
 
 // ERRORS
 define("SUCCESS","SUCCESS");
 define("LOGIN_ERROR","LOGIN_ERROR");
 define("INVALID_COORD_ERROR","INVALID_COORD_ERROR");
 define("INVALID_CHANGE_REQUEST_ERROR","INVALID_CHANGE_REQUEST_ERROR");
 define("POST_MESSAGE_LENGTH_ERROR","POST_MESSAGE_LENGTH_ERROR");
 define("SERVER_ERROR","SERVER_ERROR");
 define("ALREADY_VOTED_ERROR","ALREADY_VOTED_ERROR");
 define("DUPLICATE_ERROR","DUPLICATE_ERROR");
 define("EMPTY_RESULT","EMPTY_RESULT");
 define("PARAMETER_ERROR","PARAMETER_ERROR");
 // VALUES
 define("SPACE_RADIUS",100); // in miles
 define("NAME_CHANGE_VOTES_NEEDED",3);
 define("NAME_CHANGE_VOTES_NEEDED_AS_PERCENTAGE_OF_COMMENTS",0.1);
 
?>
